---

- name: Add docker keyring
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add docker apt repository
  apt_repository:
    repo:  deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: true

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: debug
  debug:
    var: "{{ ansible_facts['env']['USER'] }}"
  become: true

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['USER'] }}"
    append: true  # add the user to the group, without removing the other groups
    groups: docker
  become: true

