---
- name: Download Go
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ versions.go }}.linux-{{ deb_architecture[ansible_architecture] }}.tar.gz
    dest: ~/go{{ versions.go }}.linux-{{ deb_architecture[ansible_architecture] }}.tar.gz
  become: true

- name: Remove /usr/local/go
  file:
    path: /usr/local/go
    state: absent
  become: true

- name: Install Go
  shell: tar -C /usr/local -xzf ~/go{{ versions.go }}.linux-{{ deb_architecture[ansible_architecture] }}.tar.gz
  become: true

- name: Remove archive file
  file:
    state: absent
    path: ~/go{{ versions.go }}.linux-{{ deb_architecture[ansible_architecture] }}.tar.gz
  become: true

