---
- name: Download Go
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
    dest: ~/go1.23.4.linux-amd64.tar.gz
  become: true

- name: Install Go
  shell: rm -rf /usr/local/go && tar -C /usr/local -xzf ~/go1.23.4.linux-amd64.tar.gz
  become: true

- name: Remove archive file
  file:
    state: absent
    path: ~/go1.23.4.linux-amd64.tar.gz
  become: true

