---

- name: Install development tools
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:
    - name: Install devtools
      apt:
        name:
          - ripgrep
          - bat
          - htop
          - vim
          - curl
          - wget
          - git
          - rbenv
          - powerline
          - fonts-powerline
          - ca-certificates
        update_cache: true
      become: true

    - name: Change git editor to vim
      blockinfile:
        path: ~/.gitconfig
        block: |
          [core]
                  editor = vim

    - name: Configure .vimrc
      copy:
        src: .vimrc
        dest: ~/.vimrc
        mode: '0644'

    - name: Check symlinks for bat
      stat:
        path: ~/.local/bin/bat
      register: stat_result

    - name: Make symlink for bat
      shell: mkdir -p ~/.local/bin && ln -s /usr/bin/batcat ~/.local/bin/bat
      when: not stat_result.stat.exists

    - name: Install fish
      import_tasks: fish.yml

    - name: Install Go
      import_tasks: go.yml

    - name: Install gh
      import_tasks: gh.yml

    - name: Install docker
      import_tasks: docker.yml

    - name: Install kubectl
      import_tasks: kubectl.yml

    - name: Install kind
      import_tasks: kind.yml

